---
# handlers file for xenial-rdp-server

- name: start xrdp
  become: true
  service:
    name: xrdp
    state: started

- name: restart xrdp
  become: true
  service:
    name: xrdp
    state: restarted
